name: my_news
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf

flutter_native_splash:
  image: "assets/icons/logo.png"
  color: "#ffffff"
  ios_content_mode: center

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true